cote_fenetre = 480
titre_fenetre = "Jeu DK"
image_icone = "resources/img/dk_bas.png"
background = "resources/img/background.jpg"
banana = "resources/img/arrivee.png"
start = "resources/img/depart.png"
wall = "resources/img/wall.bmp"
dk_left = "resources/img/personnage.png"
dk_right = "resources/img/personnage.png"
dk_up = "resources/img/personnage.png"
dk_down = "resources/img/personnage.png"
perso = "resources/img/personnage.png"
dk_win = "resources/img/win.png"
BLUE =  (  0,   0, 255)